name: Trigger auto deployment for midilok-web

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ midilok-prod ]
    paths:
    - '//**'
    - '.github/workflows/midilok-container-deploy.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MIDILOKWEB_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: midilokregistry.azurecr.io
          registryUsername: ${{ secrets.MIDILOKWEB_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MIDILOKWEB_REGISTRY_PASSWORD }}
          containerAppName: midilok-web
          resourceGroup: midilok-prod
          imageToBuild: midilokregistry.azurecr.io/midilok-web:${{ github.sha }}
          dockerfilePath: Dockerfile

     

