name: Trigger auto deployment for midilok-capp-web

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ midilok-prod ]
    paths:
    - 'dsfsd/**'
    - '.github/workflows/midilok-capp-web-AutoDeployTrigger-3785ffb0-fd28-4b7a-a596-2441298287d4.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MIDILOKCAPPWEB_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}dsfsd 
          registryUrl: midilokregistry.azurecr.io
          registryUsername: ${{ secrets.MIDILOKCAPPWEB_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MIDILOKCAPPWEB_REGISTRY_PASSWORD }}
          containerAppName: midilok-capp-web
          resourceGroup: midilok-prod
          imageToBuild: midilokregistry.azurecr.io/midilok-capp-web:${{ github.sha }}
          dockerfilePath: Dockerfile

     

